[2023-02-01T16:01:17.552+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.spotify_etl scheduled__2023-02-01T14:00:00+00:00 [queued]>
[2023-02-01T16:01:17.559+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.spotify_etl scheduled__2023-02-01T14:00:00+00:00 [queued]>
[2023-02-01T16:01:17.559+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-01T16:01:17.559+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-02-01T16:01:17.559+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-01T16:01:17.574+0000] {taskinstance.py:1383} INFO - Executing <Task(BranchPythonOperator): spotify_etl> on 2023-02-01 14:00:00+00:00
[2023-02-01T16:01:17.577+0000] {standard_task_runner.py:55} INFO - Started process 35013 to run task
[2023-02-01T16:01:17.581+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_dag', 'spotify_etl', 'scheduled__2023-02-01T14:00:00+00:00', '--job-id', '552', '--raw', '--subdir', 'DAGS_FOLDER/airflow_dags.py', '--cfg-path', '/tmp/tmprlvfy_ek']
[2023-02-01T16:01:17.582+0000] {standard_task_runner.py:83} INFO - Job 552: Subtask spotify_etl
[2023-02-01T16:01:17.628+0000] {task_command.py:376} INFO - Running <TaskInstance: spotify_dag.spotify_etl scheduled__2023-02-01T14:00:00+00:00 [running]> on host ip-172-31-26-59.ap-northeast-2.compute.internal
[2023-02-01T16:01:17.660+0000] {logging_mixin.py:120} WARNING - /home/ubuntu/.local/lib/python3.10/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-02-01T16:01:17.683+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nywkim@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=spotify_etl
AIRFLOW_CTX_EXECUTION_DATE=2023-02-01T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-01T14:00:00+00:00
[2023-02-01T16:01:23.473+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 211, in execute
    branch = super().execute(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/spotify_dag/spotify_dags.py", line 69, in find_songs
    "acousticness" : features["acousticness"],
KeyError: 'acousticness'
[2023-02-01T16:01:23.476+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=spotify_dag, task_id=spotify_etl, execution_date=20230201T140000, start_date=20230201T160117, end_date=20230201T160123
[2023-02-01T16:01:23.489+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 552 for task spotify_etl ('acousticness'; 35013)
[2023-02-01T16:01:23.521+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-02-01T16:01:23.552+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
